

// Generated by https://quicktype.io

export interface DivisaInfo {
  [x: string]: any;
  AUDUSD: Audusd;
  CADMXN: Audusd;
  CHFMXN: Audusd;
  EURMXN: Audusd;
  EURUSD: Audusd;
  GBPMXN: Audusd;
  GBPUSD: Audusd;
  USDCAD: Audusd;
  USDJPY: Audusd;
  USDMXN: Audusd;
  tiempo: string;
}

export interface Audusd {
  precio:    number;
  "cambio%": number;
  cambio$:   number;
}
